source :gemcutter
source "http://gems.github.com"

gem "rails", "2.3.8"

gem "i18n", "~> 0.4.0"
gem "mysql", "2.8.1"
gem "rubyforge", "2.0.4"
#gem "adzap-ar_mailer"
gem "Ascii85"
gem "chronic"
gem "daemons"
gem "eventmachine"
gem "exifr"
gem "fast_xs"
gem "fastercsv"
gem "fiveruns-memcache-client"
gem "flay"
gem "flog"
#gem "gbarcode"
gem "gdata"
gem "geokit"
gem "geonames"
gem "highline"
gem "hoe", "2.6.2"
gem "jscruggs-metric_fu"
gem "json_pure"
gem "mail"
gem "mechanize", "1.0.0"
gem "memcache-client"
gem "mime-types"
gem "mojombo-chronic"
gem "net-scp"
gem "net-sftp"
gem "net-ssh"
gem "net-ssh-gateway"
gem "nokogiri"
gem "pdf-reader"
gem "polyglot"
gem "prawn"
gem "prawn-core"
gem "prawn-layout"
gem "prawn-security"
gem "rack"
gem "rake", "0.8.7"
gem "relevance-rcov"
gem "rmagick", "2.13.1"
gem "ruby-gmail"
gem "ruby_parser"
gem "sanitize"
gem "sexp_processor"
gem "shared-mime-info"
gem "treetop"
gem "zip"
gem "hpricot"
gem "koala"

group :development do
  gem "rspec-rails", "1.3.3"
  gem "cucumber-rails", "0.3.2"
  gem "database_cleaner", "0.5.0"
  gem "webrat", "0.7.1"
  gem "selenium-client", "1.2.18"
  gem "sqlite3-ruby", "1.3.1"
  #gem "mongrel", "1.1.5"
  gem "active_workbench", "~> 0.0.1"
  #gem "unicorn"
end

group :test do

end

group :production do

end