development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: MasterControl
  pool: 5
  username: root
  password: silver
  host: 127.0.0.1

test: &test
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: MasterControl
  pool: 5
  username: root
  password: silver
  socket: /run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: true
  database: MasterControl
  pool: 5
  username: root
  password: silver
  host: 127.0.0.1
